version: '3.8'

services:
  portfolio:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_URL=mongodb://mongodb:27017/LazyFlix
    depends_on:
      - mongodb
    env_file: .env # Specify environment variables

  mongodb:
    image: mongo
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
